baseurl             = "https://timthoughts.com/"   # Your domain name. Must end with "/"
languageCode        = "en-us"
title               = "Tim Thoughts"
theme = "hugo-theme-introduction"
enforce_ssl         = false
builddrafts         = false                         # Include pages with draft status of true
canonifyurls        = true                          # Turns relative urls into absolute urls
# disqusshortname   = "xxx"                         # Enable Disqus for comments
# googleAnalytics   = "xxx"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]


[params]
    bloghead        = "Blog"                        # Full name shows on blog post pages
    firstname       = "Timmy"                # First name shows in introduction on main page
    tagline         = "I'm an activist."       # Appears after the introduction
    introheight     = "full-height"                       # Input either 'medium' or 'large' or 'fullheight'
    theme           = "light"                        # Choose 'light' or 'dark'
    avatar          = "img/headshot.jpg"
    prof            = "img/wedding.jpg"
    email           = "phan.timothyv@gmail.com"         # Shows in contact section, or leave blank to omit
    localtime       = true                          # Show your current local time in contact section
    timezone        = "America/Los_Angeles"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    dateform        = "Jan 2, 2006"
    dateformfull    = "Mon Jan 2 2006 15:04:05 EST"
    cachebuster     = false                         # Add the current unix timestamp in query string for cache busting css assets (relevant in development mode)
    description     = "Website Description"         # Max 160 characters show in search results
    faviconfile     = "img/fav.ico"
    highlightjs     = true                          # Syntax highlighting
    footertext      = ""                            # Text to show in footer (overrides default text)
    fadein          = true                          # Turn on/off the fade-in effect

    showblog            = true                      # Show Blog section on home page
    showprojects        = true                      # Show Projects section on home page
    projectcolumns      = "2"                       # Choose "2" or "3" columns for projects section
    placeholderimg      = "/img/workday.jpg"        # For Projects without image
    showallposts        = true                     # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
    showlatest          = false                      # Show latest blog post summary
    sharebuttons        = true                      # On post pages, show share this social buttons

    # Share buttons
    sharetwitter        = true
    sharefacebook       = true
    sharepinterest      = false
    sharegoogleplus     = true

# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

[[params.social]]
    url = "https://twitter.com/timothyphan"
    icon = "twitter"

[[params.social]]
    url = "https://facebook.com/phan.timothy7"
    icon = "facebook"

[[params.social]]
    url = "https://linkedin.com/timothyphan7"
    icon = "linkedin"
